name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          VITE_WALLPAPER_API_URL: ${{ secrets.VITE_WALLPAPER_API_URL }}
          VITE_USE_CUSTOM_DOMAIN: ${{ vars.VITE_USE_CUSTOM_DOMAIN }}
          NODE_ENV: production
      
      - name: Add .nojekyll file
        run: touch ./dist/.nojekyll
      
      - name: Add CNAME file (if custom domain is set)
        if: vars.CUSTOM_DOMAIN != ''
        run: echo "${{ vars.CUSTOM_DOMAIN }}" > ./dist/CNAME
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'
